# Generated by Django 5.1.6 on 2025-02-17 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_quantity', to='shop.inventory'),
        ),
    ]
