# Generated by Django 5.1.6 on 2025-02-17 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_desc_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_discounts', to='shop.discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_quantity', to='shop.inventory'),
        ),
    ]
